spring:
  config:
    import:
    - optional:file:.env[.properties]
  application:
    name: account-payable-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:account_payable_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:12345}
  kafka:
    bootstrap-servers:
    - ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      group-id: account-payable-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
    listener:
      ack-mode: record
      concurrency: ${KAFKA_CONCURRENCY:3}

server:
  port: ${PORT:8003}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${PUBLIC_HOST:localhost}
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 15
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/